/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/ui/badge.vue')['default']
    Button: typeof import('./components/ui/button.vue')['default']
    Card: typeof import('./components/ui/card.vue')['default']
    CardContent: typeof import('./components/ui/card-content.vue')['default']
    CardDescription: typeof import('./components/ui/card-description.vue')['default']
    CardFooter: typeof import('./components/ui/card-footer.vue')['default']
    CardHeader: typeof import('./components/ui/card-header.vue')['default']
    CardTitle: typeof import('./components/ui/card-title.vue')['default']
    Checkbox: typeof import('./components/ui/checkbox.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogRoot: typeof import('./components/ui/dialog/DialogRoot.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Input: typeof import('./components/ui/input.vue')['default']
    Label: typeof import('./components/ui/label.vue')['default']
    LabelText: typeof import('./components/ui/label-text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./components/ui/separator.vue')['default']
    Sheet: typeof import('./components/ui/sheet/Sheet.vue')['default']
    SheetContent: typeof import('./components/ui/sheet/SheetContent.vue')['default']
    SheetTrigger: typeof import('./components/ui/sheet/SheetTrigger.vue')['default']
    Skeleton: typeof import('./components/ui/skeleton.vue')['default']
    Table: typeof import('./components/ui/table.vue')['default']
    TableBody: typeof import('./components/ui/table-body.vue')['default']
    TableCell: typeof import('./components/ui/table-cell.vue')['default']
    TableFooter: typeof import('./components/ui/table-footer.vue')['default']
    TableHead: typeof import('./components/ui/table-head.vue')['default']
    TableHeader: typeof import('./components/ui/table-header.vue')['default']
    TableRow: typeof import('./components/ui/table-row.vue')['default']
  }
}
